### ISSUE TITLE
crashes if item in csv is blank. quick fix. 

### ISSUE THREAD

**Issue by stonkpunk** [brahim-slimani/csv2json#1]
crashes if item in csv is blank- eg if you have a row like -- item, item, item,,,item

parser.js line 15:
 (object[current.trim()] = values[index].trim(), object), {});
TypeError: Cannot read property 'trim' of undefined

 easy fix with small change to parser.js line 15

 (object[current.trim()] = (values[index]+"").trim(), object), {});

**Comment by brahim-slimani** [comment]
@stonkpunk the issue has been fixed, thanks for your contribution :)
